[2020-11-10 16:17:40,737] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(ioAj) Running..........
[2020-11-10 16:17:40,739] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(YprQ) Running..........
[2020-11-10 16:17:40,748] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5004/ (Press CTRL+C to quit)
[2020-12-02 19:33:14,325] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(YTWL) Running..........
[2020-12-02 19:33:14,328] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(ZvNF) Running..........
[2020-12-02 19:33:14,337] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2020-12-02 20:24:15,641] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(eBZl) Running..........
[2020-12-02 20:24:15,643] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(qQFf) Running..........
[2020-12-02 20:24:15,654] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2020-12-03 17:59:02,205] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(QQHw) Running..........
[2020-12-03 17:59:02,208] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(UHBC) Running..........
[2020-12-03 17:59:03,164] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2020-12-03 17:59:29,466] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(uAKd) Running..........
[2020-12-03 17:59:29,470] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(drdL) Running..........
[2020-12-03 17:59:29,476] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2020-12-03 18:00:04,093] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [03/Dec/2020 18:00:04] "[33mPOST /anuvaad-etl/translator/v1/tmx/bulk/create/xls-upload HTTP/1.1[0m" 404 -
[2020-12-03 18:00:26,881] {loghandler.py:78} Thread-2 ERROR in loghandler: Something went wrong: 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "C:\Users\Vishal\Desktop\new-repo\anuvaad\anuvaad-etl\anuvaad-translator\translator\controller\translatorcontroller.py", line 52, in text_translate
    error = validator.validate_text_translate(data)
  File "C:\Users\Vishal\Desktop\new-repo\anuvaad\anuvaad-etl\anuvaad-translator\translator\validator\translatorvalidator.py", line 51, in validate_text_translate
    if 'input' not in data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
[2020-12-03 18:00:26,978] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [03/Dec/2020 18:00:26] "[31m[1mPOST /anuvaad-etl/translator/v1/text/translate HTTP/1.1[0m" 400 -
[2020-12-03 18:00:56,086] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [03/Dec/2020 18:00:56] "[33mPOST /anuvaad-etl/translator//v1/tmx/create HTTP/1.1[0m" 404 -
[2020-12-03 18:02:26,081] {loghandler.py:21} TranslatorConsumer-Instance-0 INFO in loghandler: Translator-Core-(MKkO) Running..........
[2020-12-03 18:02:26,086] {loghandler.py:21} TranslatorNMTConsumer-Instance-0 INFO in loghandler: Translator-NMT-(oJIF) Running..........
[2020-12-03 18:02:26,096] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2020-12-03 18:02:35,157] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/translator/v1/tmx/bulk/create/xls-upload [POST]
Traceback (most recent call last):
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Vishal\Desktop\new-repo\anuvaad\anuvaad-etl\anuvaad-translator\translator\controller\translatorcontroller.py", line 69, in tmx_create_bulk
    data["userID"] = request.headers["x-user-id"]
  File "C:\Users\Vishal\Desktop\anuvaad\openNMT-py\OpenNMT-py\venv\lib\site-packages\werkzeug\datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2020-12-03 18:02:35,248] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [03/Dec/2020 18:02:35] "[35m[1mPOST /anuvaad-etl/translator/v1/tmx/bulk/create/xls-upload HTTP/1.1[0m" 500 -
